export const API_CONTRACTS = {
  authLogin: '/auth/login',
  authForgotPassword: '/auth/forgot-password',
  authResetPassword: '/auth/reset-password',
  myProfile: '/auth/me',
  myPassword: '/auth/change-password',
  overview: '/overview',
  auditLog: '/audit-log',
  catalog: '/catalog/planning',
  departments: '/departments',
  departmentById: (id) => `/departments/${id}`,
  masterData: (type) => `/master-data/${type}`,
  masterDataRecord: (type, id) => `/master-data/${type}/${id}`,
  endAcademicTerm: (id) => `/master-data/terms/${id}/end`,
  requirements: '/requirements',
  requirementById: (id) => `/requirements/${id}`,
  equipment: '/equipment',
  instructorAssignments: '/instructor-assignments',
  sectionInstructors: (sectionId) => `/sections/${sectionId}/instructors`,
  sectionInstructorById: (sectionId, staffId) => `/sections/${sectionId}/instructors/${staffId}`,
  myAvailability: '/availability/me',
  confirmAvailability: '/availability/me/confirm',
  labChecks: '/lab-checks',
  labCheckByRequirement: (requirementId) => `/lab-checks/${requirementId}`,
  rooms: '/rooms',
  roomById: (roomId) => `/rooms/${roomId}`,

  draftWorkflow: (draftId) => `/schedule/drafts/${draftId}/workflow`,
  generateDraft: (draftId) => `/schedule/drafts/${draftId}/generate`,
  submitDraftReview: (draftId) => `/schedule/drafts/${draftId}/submit-review`,
  draftAllocations: (draftId) => `/schedule/drafts/${draftId}/allocations`,
  draftAllocationById: (draftId, allocationId) => `/schedule/drafts/${draftId}/allocations/${allocationId}`,
  validateDraft: (draftId) => `/schedule/drafts/${draftId}/validate`,
  publishDraft: (draftId) => `/schedule/drafts/${draftId}/publish`,
  publishedTimetable: '/timetable/published/me',

  students: '/students',
  studentCourseRegistrations: (studentId, termId) => `/students/${studentId}/course-enrollments?term_id=${encodeURIComponent(termId)}`,
  courseRegistrations: '/course-enrollments',
  courseRegistrationById: (id) => `/course-enrollments/${id}`,
  studentSectionEnrollments: (studentId, termId) => `/students/${studentId}/section-enrollments?term_id=${encodeURIComponent(termId)}`,
  sectionEnrollments: '/section-enrollments',
  sectionEnrollmentById: (id) => `/section-enrollments/${id}`,

  adminAccounts: '/admin/accounts',
  adminAccountById: (id) => `/admin/accounts/${id}`,
  adminRoles: '/admin/roles',
  adminRoleById: (id) => `/admin/roles/${id}`,
}

export const CONTRACT_NOTES = {
  overview: 'Role-aware dashboard summary calculated from the authenticated user scope.',
  audit: 'Super Admin reads immutable audit events for critical setup and scheduling operations.',
  requirements: 'Department Coordinator owns separate Lecture/Practical requirements inside the assigned department.',
  availability: 'Lecturer/TA saves a draft availability submission, then confirms it before scheduling.',
  labChecks: 'Lab Manager checks practical requirements against capacity, equipment, availability and closures.',
  registrations: 'Registration Officer registers courses only. Section assignment happens later by the Department Coordinator.',
  sectionAssignments: 'Individual student-section enrollments are the final source of truth for personal timetables and student conflict detection.',
  scheduleFlow: 'Scheduler generates/edits the draft and submits it for review. ADMIN reviews within scope and is the role that publishes. Scheduler cannot publish.',
  publishedTimetable: 'Lecturer, TA and Student accounts consume only the latest published version. Draft allocations are never exposed.',
  systemAdministration: 'Super Admin manages accounts, roles, permissions, departments, terms and audit access.',
  profile: 'Every authenticated user can update their own display name and password; role/scope stay administrator-controlled.',
  forgotPassword: 'Unauthenticated password recovery uses email + one-time reset code. The request response must stay generic to avoid account enumeration.',
}
