export const API_CONTRACTS = {
  authLogin: '/auth/login',
  overview: '/overview',
  catalog: '/catalog/planning',
  masterData: (type) => `/master-data/${type}`,
  masterDataRecord: (type, id) => `/master-data/${type}/${id}`,
  requirements: '/requirements',
  requirementById: (id) => `/requirements/${id}`,
  myAvailability: '/availability/me',
  confirmAvailability: '/availability/me/confirm',
  labChecks: '/lab-checks',
  labCheckByRequirement: (requirementId) => `/lab-checks/${requirementId}`,
  rooms: '/rooms',
  roomById: (roomId) => `/rooms/${roomId}`,
  draftAllocations: (draftId) => `/schedule/drafts/${draftId}/allocations`,
  draftAllocationById: (draftId, allocationId) => `/schedule/drafts/${draftId}/allocations/${allocationId}`,
  validateDraft: (draftId) => `/schedule/drafts/${draftId}/validate`,
  publishDraft: (draftId) => `/schedule/drafts/${draftId}/publish`,
  publishedTimetable: '/timetable/published/me',
  publicSections: '/public/sections',
  publicTimetable: (sectionId) => `/public/timetable?section_id=${encodeURIComponent(sectionId)}`,
  adminAccounts: '/admin/accounts',
  adminAccountById: (id) => `/admin/accounts/${id}`,
  adminRoles: '/admin/roles',
  adminRoleById: (id) => `/admin/roles/${id}`,
}

export const CONTRACT_NOTES = {
  overview: 'Role-aware dashboard summary. The backend calculates live metrics and recent activity from the authenticated user scope.',
  requirements: 'Coordinator owns course/section session requirements, duration, room type, equipment and preferred windows.',
  availability: 'Lecturer/TA saves a draft availability submission, then confirms it for scheduling.',
  labChecks: 'Lab manager reviews lab-session requirements against capacity, equipment, availability and closures.',
  rooms: 'Facilities users can create, edit and remove rooms/labs. The same contracts are used by mock mode now and the real backend later.',
  draftAllocations: 'Scheduler creates and edits draft allocations with course, section, staff, room, day and slot before validation and publication.',
  publish: 'Scheduler validates the current draft first. Hard conflicts block publication. A successful publish creates a new immutable published version.',
  publishedTimetable: 'Doctor/TA views consume the latest published version only; draft allocations are never exposed.',
  publicStudentTimetable: 'Students do not authenticate. The public home page lists available sections and reads the latest published timetable for the selected section only.',
  systemAdministration: 'Super Admin manages staff accounts and role definitions/permissions. Production authorization must be enforced by the backend.',
}
