import { apiRequest } from './client.js'
import { API_CONTRACTS } from './contracts.js'

export const tanseekApi = {
  getOverview: () => apiRequest(API_CONTRACTS.overview),
  getAdminAccounts: () => apiRequest(API_CONTRACTS.adminAccounts),
  createAdminAccount: (payload) => apiRequest(API_CONTRACTS.adminAccounts, { method: 'POST', body: JSON.stringify(payload) }),
  updateAdminAccount: (id, payload) => apiRequest(API_CONTRACTS.adminAccountById(id), { method: 'PUT', body: JSON.stringify(payload) }),
  deleteAdminAccount: (id) => apiRequest(API_CONTRACTS.adminAccountById(id), { method: 'DELETE' }),
  getAdminRoles: () => apiRequest(API_CONTRACTS.adminRoles),
  createAdminRole: (payload) => apiRequest(API_CONTRACTS.adminRoles, { method: 'POST', body: JSON.stringify(payload) }),
  updateAdminRole: (id, payload) => apiRequest(API_CONTRACTS.adminRoleById(id), { method: 'PUT', body: JSON.stringify(payload) }),
  deleteAdminRole: (id) => apiRequest(API_CONTRACTS.adminRoleById(id), { method: 'DELETE' }),
  getPlanningCatalog: () => apiRequest(API_CONTRACTS.catalog),
  getMasterData: (type) => apiRequest(API_CONTRACTS.masterData(type)),
  createMasterData: (type, payload) => apiRequest(API_CONTRACTS.masterData(type), { method: 'POST', body: JSON.stringify(payload) }),
  updateMasterData: (type, id, payload) => apiRequest(API_CONTRACTS.masterDataRecord(type, id), { method: 'PUT', body: JSON.stringify(payload) }),
  deleteMasterData: (type, id) => apiRequest(API_CONTRACTS.masterDataRecord(type, id), { method: 'DELETE' }),
  getRequirements: () => apiRequest(API_CONTRACTS.requirements),
  createRequirement: (payload) => apiRequest(API_CONTRACTS.requirements, { method: 'POST', body: JSON.stringify(payload) }),
  updateRequirement: (id, payload) => apiRequest(API_CONTRACTS.requirementById(id), { method: 'PUT', body: JSON.stringify(payload) }),
  getMyAvailability: (termId) => apiRequest(`${API_CONTRACTS.myAvailability}?term_id=${encodeURIComponent(termId)}`),
  saveMyAvailability: (payload) => apiRequest(API_CONTRACTS.myAvailability, { method: 'PUT', body: JSON.stringify(payload) }),
  confirmMyAvailability: (payload) => apiRequest(API_CONTRACTS.confirmAvailability, { method: 'POST', body: JSON.stringify(payload) }),
  getLabChecks: () => apiRequest(API_CONTRACTS.labChecks),
  saveLabCheck: (requirementId, payload) => apiRequest(API_CONTRACTS.labCheckByRequirement(requirementId), { method: 'POST', body: JSON.stringify(payload) }),
  getRooms: () => apiRequest(API_CONTRACTS.rooms),
  createRoom: (payload) => apiRequest(API_CONTRACTS.rooms, { method: 'POST', body: JSON.stringify(payload) }),
  updateRoom: (roomId, payload) => apiRequest(API_CONTRACTS.roomById(roomId), { method: 'PUT', body: JSON.stringify(payload) }),
  deleteRoom: (roomId) => apiRequest(API_CONTRACTS.roomById(roomId), { method: 'DELETE' }),
  getDraftAllocations: (draftId) => apiRequest(API_CONTRACTS.draftAllocations(draftId)),
  createDraftAllocation: (draftId, payload) => apiRequest(API_CONTRACTS.draftAllocations(draftId), { method: 'POST', body: JSON.stringify(payload) }),
  updateDraftAllocation: (draftId, allocationId, payload) => apiRequest(API_CONTRACTS.draftAllocationById(draftId, allocationId), { method: 'PUT', body: JSON.stringify(payload) }),
  deleteDraftAllocation: (draftId, allocationId) => apiRequest(API_CONTRACTS.draftAllocationById(draftId, allocationId), { method: 'DELETE' }),
  validateDraft: (draftId, payload = {}) => apiRequest(API_CONTRACTS.validateDraft(draftId), { method: 'POST', body: JSON.stringify(payload) }),
  publishDraft: (draftId, payload = {}) => apiRequest(API_CONTRACTS.publishDraft(draftId), { method: 'POST', body: JSON.stringify(payload) }),
  getPublishedTimetable: () => apiRequest(API_CONTRACTS.publishedTimetable),
  getPublicSections: () => apiRequest(API_CONTRACTS.publicSections),
  getPublicTimetable: (sectionId) => apiRequest(API_CONTRACTS.publicTimetable(sectionId)),
}
